$(".dice1").hover(function(){
  $(this).attr("src","images/dice2.png")
},function(){
  $(this).attr("src","images/dice1.png")
});
$(".title-image1").hover(function(){
  $(this).attr("src","images/lady.webp");
},function(){
  $(this).attr("src","images/cuppic.webp");
});
$(".title-image2").hover(function(){
  $(this).attr("src","images/cuppic2.webp");
},function(){
  $(this).attr("src","images/bottlepic.webp");
});
$(".title-image3").hover(function(){
  $(this).attr("src","images/bottlepic.webp");
},function(){
  $(this).attr("src","images/cuppic2.webp");
});
$(".title-image4").hover(function(){
  $(this).attr("src","images/cuppic.webp");
},function(){
  $(this).attr("src","images/lady.webp");
});
